# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95e5f9ec42e7db39833853576bc3005904a0d9b076c462f7a9827e74bbb1b1f3df3571f42fe53a24b118b5ed98404ad1ba14728f90d3b20847725680b2ca2f02

test:
  secret_key_base: 0c6fca629f679f44ee6929f0192cc3e569b7e77110e433df2b5523855d3479462e57b276b85f6cdb80e079f36b90588e4d319cde0f41779b11b0df6b1b0c1600

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
